name: App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python_version: ["3.10", "3.11", "3.12"]
    steps:
        - uses: actions/checkout@v4
        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python_version }}
            architecture: x64
        - name: Install dependencies
          run: |
            python -m pip install -r requirements-dev.txt
        - name: Install app as editable app
          run: |
            python -m pip install -e src/backend
        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Build frontend
          run: |
            cd ./src/frontend
            npm install
            npm run build
        - name: Run E2E tests on Windows with Playwright
          run: |
            set PLAYWRIGHT_BROWSERS_PATH=%USERPROFILE%\AppData\Local\ms-playwright
            playwright install chromium --with-deps
            python3 -m pytest tests/e2e.py --tracing=retain-on-failure
        - name: Upload test artifacts
          if: ${{ failure() && steps.e2e.conclusion == 'failure' }}
          uses: actions/upload-artifact@v4
          with:
            name: playwright-traces${{ matrix.python_version }}
            path: test-results
